<?php

require_once dirname(__FILE__) . '/../../../../lib/Kingboard/Helper/Kingboard_Helper_String.php';

/**
 * Test class for Kingboard_Helper_String.
 * Generated by PHPUnit on 2011-04-29 at 14:55:06.
 */
class Kingboard_Helper_StringTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Kingboard_Helper_String
     */
    protected $fixture;

    protected function setUp() {
        $this->fixture = Kingboard_Helper_String::getInstance();
    }

    public function testGetInstance() {
        $this->assertInstanceOf('Kingboard_Helper_String', Kingboard_Helper_String::getInstance());
        $this->assertInstanceOf('Kingboard_Helper_String', $this->fixture);
    }
    public function testStrlen() {
        $str = '12345';
        $this->assertEquals(5, $this->fixture->strlen($str));
    }

    public function testSubstr() {
         $str = '12345';
         $this->assertEquals('45', $this->fixture->substr($str, 3));
         $this->assertEquals('123', $this->fixture->substr($str, 0, 3));
    }

    public function testLower() {
        $str = 'Some String With ÖÄÜ';
        $this->assertEquals('some string with öäü', $this->fixture->lower($str));
    }

    public function testStrpos() {
        $str = 'Some String Some String';
        $this->assertEquals(5, $this->fixture->strpos('String', $str));
        $this->assertEquals(17, $this->fixture->strpos('String', $str, 6));
    }

    public function testStripos() {
        $str = 'Some String Some String';
        $this->assertEquals(5, $this->fixture->stripos('string', $str));
        $this->assertEquals(17, $this->fixture->stripos('string', $str, 6));
    }

}

?>
