<?php

/**
 * Test class for Kingboard_KillmailHash_IdHash.
 * Generated by PHPUnit on 2011-04-05 at 20:44:47.
 */
class Kingboard_KillmailHash_IdHashTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Kingboard_KillmailHash_IdHash
     */
    protected $fixture;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->fixture = new Kingboard_KillmailHash_IdHash;
    }

    public function testTime() {
        $time = time();
        $this->fixture->setTime(new MongoDate($time));
        $this->assertEquals($time, $this->fixture->getTime());
        $time = time() - 20;
        $this->fixture->setTime(new MongoDate($time));
        $this->assertEquals($time, $this->fixture->getTime());
    }

    public function testVictimId() {
        $this->fixture->setVictimId(1234);
        $this->assertEquals(1234, $this->fixture->getVictimId());
        $this->fixture->setVictimId(-4);
        $this->assertEquals(1234, $this->fixture->getVictimId());
    }

    public function testAttackerIds() {
        $this->fixture->addAttacker('asd dss');
        $this->fixture->addAttacker('');
        $this->fixture->addAttacker('+e dSSd');
        $this->assertEquals(array('asddss','edssd'), $this->fixture->getAttackers());
        $this->fixture->setAttackers(array('Ols a', 'sOp ,l'));
        $this->assertEquals(array('asddss','edssd', 'olsa', 'sopl'), $this->fixture->getAttackers());
    }

    public function testFinalBlowAttacker() {
        $this->fixture->setFinalBlowAttacker('aaa');
        $this->assertEquals('', $this->fixture->getFinalBlowAttacker());
        $this->fixture->addAttacker('aaa');
        $this->fixture->setFinalBlowAttacker('aaa');
        $this->assertEquals('aaa', $this->fixture->getFinalBlowAttacker());
        $this->fixture->setFinalBlowAttacker('bbb');
        $this->assertEquals('aaa', $this->fixture->getFinalBlowAttacker());
    }


    public function testGenerateHash() {
        $time = time() - 4000;
        $this->fixture->setAttackers(array('aaa', 'bbb'))
                      ->setTime(new MongoDate($time))
                      ->setVictimId(3)
                      ->setVictimShip(4)
                      ->setFinalBlowAttacker('aaa');
        $actual = $this->fixture->generateHash();
        $expected = sha1($time . '34aaabbbaaa');
        $this->assertEquals($expected, $actual);
    }

    public function testGenerateHashWithoutParamsRaisesException() {
        $this->setExpectedException('Kingboard_KillmailHash_ErrorException');
        $this->fixture->generateHash();
    }

    public function testToString() {
        $this->fixture->setAttackers(array('aaa', 'bbb'))
                      ->setTime(new MongoDate(time() - 4000))
                      ->setVictimId(3)
                      ->setVictimShip(4)
                      ->setFinalBlowAttacker('aaa');
        $expected = $this->fixture->generateHash();
        $actual = (string) $this->fixture;
        $this->assertEquals($expected, $actual);
        $actual = $this->fixture->__toString();
        $this->assertEquals($expected, $actual);
    }

}

?>
