SithTemplate: TemplateStdLibExPlugin Class Reference
TemplateStdLibExPlugin Class Reference
New StdLibEx plugin, which combines old CoreTags, CoreFilters and CoreHooks.
Public Member Functions
providedTags ()
Provided tags.
providedFilters ()
Provided filters.
providedHooks ()
Provided hooks.
providedHandlers ()
Provided handlers.
handleTAutoEscape (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% autoescape %} tag.
handleTBlock (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% block %} tag.
handleTCycle (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% cycle %} tag.
handleTDebug (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% debug %} tag.
handleTExtends (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% extends %} tag.
handleTFilter (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% filter %} tag.
handleTFirstOf (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% firstof %} tag.
handleTFor (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% for %} tag.
handleTEmpty (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% empty %} tag.
handleTIfChanged (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% ifchanged %} tag.
handleTIf (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% if %} tag.
handleTElse (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% else %} tag.
handleTElseIf (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% elseif %} tag.
handleTIfEqual (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% ifequal %} tag.
handleTIfNotEqual (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% ifnotequal %} tag.
handleTInclude (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% include %} tag.
handleTNow (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% now %} tag.
handleTSpaceless (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% spaceless %} tag.
handleTTemplateTag (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% templatetag %} tag.
handleTWidthRatio (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% widthratio %} tag.
handleTWith (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% with %} tag.
handleTPutBlock (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% putblock %} tag.
handleTCall (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% call %} tag.
handleTMeta (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
{% meta %} tag.
handleFAdd (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
add filter.
handleFAddSlashes (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
addslashes filter.
handleFCapFirst (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
capfirst filter.
handleFCut (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
cut filter.
handleFDate (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
date filter.
handleFDefault (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
default filter.
handleFDefaultIfNone (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
default_if_none filter.
handleFDivisibleBy (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
divisibleby filter.
handleFEscape (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
escape filter.
handleFFileSizeFormat (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
filesizeformat filter.
handleFFixAmpersands (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
fix_ampersands filter.
handleFJoin (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
join filter.
handleFLength (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
length filter.
handleFLengthIs (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
length_is filter.
handleFLineBreaks (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
linebreaks filter.
handleFLineBreaksBR (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
linebreaksbr filter.
handleFLJust (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
ljust filter.
handleFLower (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
lower filter.
handleFMakeList (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
make_list filter.
handleFPluralize (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
pluralize filter.
handleFRandom (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
random filter.
handleFRemoveTags (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
removetags filter.
handleFRJust (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
rjust filter.
handleFSlugify (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
slugify filter.
handleFTitle (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
title filter.
handleFUpper (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
upper filter.
handleFURLEncode (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
urlencode filter.
handleFURLDecode (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
urldecode filter.
handleFWordCount (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
wordcount filter.
handleFWordWrap (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, array &$args)
wordwrap filter.
handleHAutoEscape (TemplateCompilerEx $compiler, array &$filterChain)
Auto-escaping hook.
handleHInternalVariable (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$variableCode, &$variableCheck)
{{ internal }} variable handler.
handleHForLoopVariable (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$variableCode, &$variableCheck)
{{ forloop }} variable handler.
handleHBlockVariable (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$variableCode, &$variableCheck)
{{ block }} variable handler.
Private Member Functions
parseIfExpressionNonEmpty ($x)
parseIfExpressionCheckParens (TemplateCompilerEx $compiler, TemplateNodeEx $node, $level, $final=false)
parseIfExpression (TemplateCompilerEx $compiler, TemplateNodeEx $node, $expression)
commonIfEqual (TemplateCompilerEx $compiler, TemplateNodeEx $node, array $variables, $operator)
commonFJust ($sign, TemplateCompilerEx $compiler, TemplateNodeEx $node, &$filter, &$width)
Detailed Description
New StdLibEx plugin, which combines old CoreTags, CoreFilters and CoreHooks.
Since there is no more distinction between compile-time and run-time plugins, everything is provided within single class, to save I/O and object allocations.
Definition at line 685 of file StdLibEx.plugin.php.
Member Function Documentation
TemplateStdLibExPlugin::providedTags ()
Provided tags.
See Standard tags.
Returns:
Array of handlers
Definition at line 693 of file StdLibEx.plugin.php.
Referenced by providedHandlers().
TemplateStdLibExPlugin::providedFilters ()
Provided filters.
See Standard filters.
Returns:
Array of handlers
Definition at line 728 of file StdLibEx.plugin.php.
Referenced by providedHandlers().
TemplateStdLibExPlugin::providedHooks ()
Provided hooks.
Returns:
Array of handlers
Definition at line 768 of file StdLibEx.plugin.php.
Referenced by providedHandlers().
TemplateStdLibExPlugin::providedHandlers ()
Provided handlers.
See Standard library.
Returns:
Array of handlers
See also:
ITemplatePlugin::providedHandlers
Implements ITemplatePlugin.
Definition at line 786 of file StdLibEx.plugin.php.
References providedFilters(), providedHooks(), and providedTags().
TemplateStdLibExPlugin::handleTAutoEscape (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% autoescape %} tag.
Definition at line 799 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::handleChildren(), and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTBlock (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% block %} tag.
Definition at line 816 of file StdLibEx.plugin.php.
References TemplateCompilerEx::createBlock(), TemplateError::E_INVALID_ARGUMENT, and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTCycle (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% cycle %} tag.
Definition at line 843 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateError::E_INVALID_SYNTAX, TemplateUtils::panic(), TemplateCompilerEx::parseVariableExpression(), and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTDebug (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% debug %} tag.
Definition at line 906 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleTExtends (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% extends %} tag.
Definition at line 911 of file StdLibEx.plugin.php.
References TemplateUtils::checkIORestriction(), TemplateError::E_INVALID_SYNTAX, and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTFilter (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% filter %} tag.
Definition at line 931 of file StdLibEx.plugin.php.
References TemplateCompilerEx::createBlock(), and TemplateCompilerEx::parseFilterChain().
TemplateStdLibExPlugin::handleTFirstOf (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% firstof %} tag.
Definition at line 943 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::parseVariableExpression(), and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTFor (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% for %} tag.
Definition at line 975 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::findAlternativeBranch(), TemplateCompilerEx::generateUniqueBlock(), TemplateCompilerEx::handleChildren(), TemplateCompilerEx::parseVariableExpression(), TemplateCompilerEx::raise(), TemplateCompilerEx::raiseIf(), TemplateUtils::sanitize(), and TemplateUtils::split().
TemplateStdLibExPlugin::handleTEmpty (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% empty %} tag.
Definition at line 1112 of file StdLibEx.plugin.php.
References TemplateUtils::panic().
TemplateStdLibExPlugin::handleTIfChanged (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% ifchanged %} tag.
Definition at line 1120 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::findAlternativeBranch(), TemplateCompilerEx::generateUniqueBlock(), TemplateCompilerEx::handleChildren(), TemplateCompilerEx::parseVariableExpression(), TemplateCompilerEx::raiseIf(), and TemplateUtils::sanitize().
TemplateStdLibExPlugin::parseIfExpressionNonEmpty ($ x) [private]
Definition at line 1175 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::parseIfExpressionCheckParens (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, $ level, $ final = false) [private]
Definition at line 1178 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, and TemplateCompilerEx::raiseIf().
Referenced by parseIfExpression().
TemplateStdLibExPlugin::parseIfExpression (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, $ expression) [private]
Definition at line 1192 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::parseFilterChain(), parseIfExpressionCheckParens(), TemplateCompilerEx::parseVariableExpression(), TemplateCompilerEx::raiseIf(), and TemplateUtils::split().
TemplateStdLibExPlugin::handleTIf (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% if %} tag.
Definition at line 1300 of file StdLibEx.plugin.php.
References TemplateCompilerEx::handleChildren().
TemplateStdLibExPlugin::handleTElse (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% else %} tag.
Definition at line 1308 of file StdLibEx.plugin.php.
References TemplateUtils::panic().
TemplateStdLibExPlugin::handleTElseIf (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% elseif %} tag.
Definition at line 1316 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::commonIfEqual (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, array $ variables, $ operator) [private]
Definition at line 1321 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateCompilerEx::handleChildren(), TemplateCompilerEx::parseFilterChain(), TemplateCompilerEx::parseVariableExpression(), TemplateCompilerEx::raiseIf(), and TemplateUtils::split().
Referenced by handleTIfEqual(), and handleTIfNotEqual().
TemplateStdLibExPlugin::handleTIfEqual (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% ifequal %} tag.
Definition at line 1342 of file StdLibEx.plugin.php.
References commonIfEqual().
TemplateStdLibExPlugin::handleTIfNotEqual (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% ifnotequal %} tag.
Definition at line 1347 of file StdLibEx.plugin.php.
References commonIfEqual().
TemplateStdLibExPlugin::handleTInclude (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% include %} tag.
Definition at line 1352 of file StdLibEx.plugin.php.
References TemplateUtils::escape(), and TemplateCompilerEx::parseVariableExpression().
TemplateStdLibExPlugin::handleTNow (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% now %} tag.
Definition at line 1369 of file StdLibEx.plugin.php.
References TemplateCompilerEx::parseFilterChain(), TemplateCompilerEx::parseVariableExpression(), and TemplateUtils::split().
TemplateStdLibExPlugin::handleTSpaceless (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% spaceless %} tag.
Definition at line 1383 of file StdLibEx.plugin.php.
References TemplateCompilerEx::handleChildren().
TemplateStdLibExPlugin::handleTTemplateTag (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% templatetag %} tag.
Definition at line 1394 of file StdLibEx.plugin.php.
References TemplateError::E_INVALID_ARGUMENT, and TemplateCompilerEx::raiseIf().
TemplateStdLibExPlugin::handleTWidthRatio (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% widthratio %} tag.
Definition at line 1431 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleTWith (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% with %} tag.
Definition at line 1458 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleTPutBlock (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% putblock %} tag.
Definition at line 1481 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleTCall (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% call %} tag.
Definition at line 1504 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleTMeta (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args)
{% meta %} tag.
Definition at line 1543 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFAdd (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
add filter.
Definition at line 1557 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFAddSlashes (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
addslashes filter.
Definition at line 1565 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFCapFirst (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
capfirst filter.
Definition at line 1570 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFCut (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
cut filter.
Definition at line 1575 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFDate (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
date filter.
Definition at line 1587 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFDefault (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
default filter.
Definition at line 1592 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFDefaultIfNone (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
default_if_none filter.
Definition at line 1597 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFDivisibleBy (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
divisibleby filter.
Definition at line 1602 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFEscape (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
escape filter.
Definition at line 1623 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFFileSizeFormat (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
filesizeformat filter.
Definition at line 1628 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFFixAmpersands (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
fix_ampersands filter.
Definition at line 1645 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFJoin (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
join filter.
Definition at line 1650 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLength (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
length filter.
Definition at line 1655 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLengthIs (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
length_is filter.
Definition at line 1660 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLineBreaks (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
linebreaks filter.
Definition at line 1665 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLineBreaksBR (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
linebreaksbr filter.
Definition at line 1678 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::commonFJust ($ sign, TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, &$ width) [private]
Definition at line 1683 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLJust (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
ljust filter.
Definition at line 1700 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFLower (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
lower filter.
Definition at line 1705 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFMakeList (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
make_list filter.
Definition at line 1710 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFPluralize (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
pluralize filter.
Definition at line 1715 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFRandom (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
random filter.
Definition at line 1742 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFRemoveTags (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
removetags filter.
Definition at line 1751 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFRJust (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
rjust filter.
Definition at line 1756 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFSlugify (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
slugify filter.
Definition at line 1761 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFTitle (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
title filter.
Definition at line 1775 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFUpper (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
upper filter.
Definition at line 1780 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFURLEncode (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
urlencode filter.
Definition at line 1785 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFURLDecode (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
urldecode filter.
Definition at line 1790 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFWordCount (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
wordcount filter.
Definition at line 1795 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleFWordWrap (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ filter, array &$ args)
wordwrap filter.
Definition at line 1800 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleHAutoEscape (TemplateCompilerEx $ compiler, array &$ filterChain)
Auto-escaping hook.
Hooked into parseFilterChain:entry.
Definition at line 1812 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleHInternalVariable (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ variableCode, &$ variableCheck)
{{ internal }} variable handler.
Hooked into parseVariableExpression:postCodeGen.
Definition at line 1844 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleHForLoopVariable (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ variableCode, &$ variableCheck)
{{ forloop }} variable handler.
Hooked into parseVariableExpression:postCodeGen.
Definition at line 1896 of file StdLibEx.plugin.php.
TemplateStdLibExPlugin::handleHBlockVariable (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ variableCode, &$ variableCheck)
{{ block }} variable handler.
Hooked into parseVariableExpression:postCodeGen.
Definition at line 1909 of file StdLibEx.plugin.php.
The documentation for this class was generated from the following file:
StdLibEx.plugin.php