SithTemplate: TemplateUtils Class Reference
TemplateUtils Class Reference
Namespace-acting all-static class.
Static Public Member Functions
static escape ($str)
Escape string to use in template class.
static sanitize ($str)
Sanitize string, for use as function name.
static strip ($str)
Strip newlines and spaces from string.
static split ($separator, $str, $reverse=false)
Split string into two.
static splitEscaped ($delimiter, $expression)
Properly splits given expression using given delimiter.
static filterEmpty ($x)
static doesImplement ($classOrObject, $interface)
Check whether class implements given interface.
static splitIODSN (array &$settings, $dsn)
Splits I/O DSN into driver name and template name.
static parseIODSN (array &$settings, $dsn)
Splits I/O DSN, and creates correct driver object.
static className ($template)
Returns class name for given template or DSN.
static panic ($file, $line)
Panics.
static checkIfAllowed ($obj, $type, $name, $node=null)
Checks whether element is allowed.
static checkIORestriction ($obj, $setting, $dsn, $expectedDriver, $node=null)
Checks whether I/O restriction is in effect.
Detailed Description
Namespace-acting all-static class.
Definition at line 12 of file Utils.php.
Member Function Documentation
static TemplateUtils::escape ($ str) [static]
Escape string to use in template class.
Parameters:
[in] $str String
Returns:
Escaped string
Definition at line 19 of file Utils.php.
Referenced by TemplateStdLibExPlugin::handleTInclude(), TemplateCompilerEx::parseFilterChain(), and TemplateCompilerEx::parseVariableExpression().
static TemplateUtils::sanitize ($ str) [static]
Sanitize string, for use as function name.
Parameters:
[in] $str String
Returns:
Sanitized string
Definition at line 35 of file Utils.php.
Referenced by TemplateStdLibExPlugin::handleTFor(), and TemplateStdLibExPlugin::handleTIfChanged().
static TemplateUtils::strip ($ str) [static]
Strip newlines and spaces from string.
Parameters:
[in] $str String
Returns:
Stripped string
Definition at line 45 of file Utils.php.
Referenced by TemplateCompilerEx::commonVerifyElement(), and TemplateCompilerEx::runHooks().
static TemplateUtils::split ($ separator, $ str, $ reverse = false) [static]
Split string into two.
Parameters:
[in] $separator Separator
[in] $str String to split
[in] $reverse Use reversed search
Returns:
Array
Definition at line 57 of file Utils.php.
Referenced by TemplateStdLibExPlugin::commonIfEqual(), TemplateStdLibExPlugin::handleTFor(), TemplateStdLibExPlugin::handleTNow(), TemplateCompilerEx::parseFilterChain(), TemplateStdLibExPlugin::parseIfExpression(), TemplateCompilerEx::parserGetNextToken(), and splitIODSN().
static TemplateUtils::splitEscaped ($ delimiter, $ expression) [static]
Properly splits given expression using given delimiter.
Supports string delimiter escaping (\").
Parameters:
[in] $delimiter Delimiter to use
[in] $expression Expression to split
Returns:
Split expression
Todo:
Better way?
Definition at line 79 of file Utils.php.
References panic().
Referenced by TemplateCompilerEx::parseFilterChain(), and TemplateCompilerEx::parserGetNextToken().
static TemplateUtils::filterEmpty ($ x) [static]
Definition at line 118 of file Utils.php.
static TemplateUtils::doesImplement ($ classOrObject, $ interface) [static]
Check whether class implements given interface.
Parameters:
[in] $classOrObject Mixed
[in] $interface String
Returns:
Boolean
Definition at line 127 of file Utils.php.
Referenced by TemplatePlugins::load().
static TemplateUtils::splitIODSN (array &$ settings, $ dsn) [static]
Splits I/O DSN into driver name and template name.
Parameters:
[in] $settings Settings array
[in] $dsn DSN to split
Returns:
Array(driver name, template name)
Definition at line 138 of file Utils.php.
References split().
Referenced by checkIORestriction(), and parseIODSN().
static TemplateUtils::parseIODSN (array &$ settings, $ dsn) [static]
Splits I/O DSN, and creates correct driver object.
Parameters:
[in] $settings Settings array
[in] $dsn DSN to parse
Returns:
Array(I/O driver, template name)
Definition at line 153 of file Utils.php.
References TemplateIO::get(), and splitIODSN().
Referenced by TemplateCompilerEx::compile(), and TemplateEnviron::include_().
static TemplateUtils::className ($ template) [static]
Returns class name for given template or DSN.
Note that only real template name should be used in class name.
Parameters:
[in] $template Template name
Returns:
Class name
Definition at line 165 of file Utils.php.
References panic().
static TemplateUtils::panic ($ file, $ line) [static]
Panics.
Used internally when sanity checks are failing.
Parameters:
[in] $file Source filename
[in] $line Source line
Definition at line 176 of file Utils.php.
References TemplateError::E_INTERNAL_CORE_FAILURE.
Referenced by checkIfAllowed(), checkIORestriction(), className(), TemplateCompilerEx::commonVerifyElement(), TemplateCompilerEx::generateUniqueBlock(), TemplateStdLibExPlugin::handleTCycle(), TemplateStdLibExPlugin::handleTElse(), TemplateStdLibExPlugin::handleTEmpty(), and splitEscaped().
static TemplateUtils::checkIfAllowed ($ obj, $ type, $ name, $ node = null) [static]
Checks whether element is allowed.
Raises TemplateError if it's not.
Parameters:
[in] $obj Instance of TemplateEnviron or TemplateCompilerEx
[in] $type Element type ('plugin', 'tag', 'filter', 'function')
[in] $name Element name
[in] $node Optional instance of TemplateNodeEx
Definition at line 191 of file Utils.php.
References TemplateError::E_SECURITY_VIOLATION, panic(), TemplateEnviron::SECURITY_ALLOW_ALL, TemplateEnviron::SECURITY_ALLOW_DENY, TemplateEnviron::SECURITY_DENY_ALL, TemplateEnviron::SECURITY_DENY_ALLOW, and TemplateEnviron::SECURITY_DISABLE.
Referenced by TemplateCompilerEx::commonVerifyElement(), and TemplatePlugins::load().
static TemplateUtils::checkIORestriction ($ obj, $ setting, $ dsn, $ expectedDriver, $ node = null) [static]
Checks whether I/O restriction is in effect.
Raises TemplateError if setting is active and driver names mismatch.
Parameters:
[in] $obj Instance of TemplateEnviron or TemplateCompilerEx
[in] $setting Setting to check (either restrictExtendIO or restrictIncludeIO)
[in] $dsn DSN to check
[in] $expectedDriver Expected driver name
[in] $node Optional instance of TemplateNodeEx
Definition at line 274 of file Utils.php.
References TemplateError::E_SECURITY_VIOLATION, panic(), and splitIODSN().
Referenced by TemplateStdLibExPlugin::handleTExtends().
The documentation for this class was generated from the following file:
Utils.php