SithTemplate: TemplateEnviron Class Reference
TemplateEnviron Class Reference
Template environment - library's end-user API.
Public Member Functions
__construct (array $settings=array())
Constructor.
compile (ITemplateIODriver $io, $template)
Compile given template.
include_ ($template, $mode=null, $returnMeta=false)
Includes template's code into global namespace via I/O driver given in DSN.
get ($template, $mode=null)
Returns template instance.
getMeta ($template, $mode=null)
Returns user-defined template metadata.
cachedGet ($template, $mode=null)
Cached version of TemplateEnviron::get.
render ($template, array $context, $mode=null)
Render the template directly.
Static Public Member Functions
static createFromINI ($settingsINI)
Named constructor.
Public Attributes
const RECOMPILE_ALWAYS = 1
One of recompilation modes - always recompile.
const RECOMPILE_IF_CHANGED = 0
One of recompilation modes - recompile only when necessary (default).
const RECOMPILE_NEVER = -1
One of recompilation modes - never recompile (a.k.a.
const SECURITY_DISABLE = 0
One of security modes - do not test against the lists.
const SECURITY_ALLOW_ALL = 1
One of security modes - first allow all, then check 'disallowed' list.
const SECURITY_ALLOW_DENY = 2
One of security modes - first check 'allowed' list, then 'disallowed'.
const SECURITY_DENY_ALLOW = 3
One of security modes - first check 'disallowed' list, then 'allowed'.
const SECURITY_DENY_ALL = 4
One of security modes - first disallow all, then check 'allowed' list.
const SECURITY_MATCH_EVERYTHING = true
May be used instead of allowed or disallowed list, as a wildcard matching everything.
const LOAD_ALL_PLUGINS = true
May be used as loadPlugins setting to always load all available plugins on all search paths.
$settings
Default environment settings.
$templateCache = array()
Internal template objects cache.
$compiler = null
Compiler instance.
Detailed Description
Template environment - library's end-user API.
Examples:
00_hello.php, 01_io.php, 02_settings.php, 03_context.php, 08_security.php, and 09_errors.php.
Definition at line 198 of file Environment.php.
Constructor & Destructor Documentation
TemplateEnviron::__construct (array $ settings = array())
Constructor.
Optionally sets up initial settings.
Parameters:
[in] $settings Settings array
See also:
TemplateEnviron::$settings
Definition at line 412 of file Environment.php.
References $settings.
Member Function Documentation
static TemplateEnviron::createFromINI ($ settingsINI) [static]
Named constructor.
Shorthand for INI parsing.
Parameters:
[in] $settingsINI Settings INI filename
Returns:
TemplateEnviron instance
See also:
TemplateEnviron::__construct
Examples:
02_settings.php.
Definition at line 426 of file Environment.php.
TemplateEnviron::compile (ITemplateIODriver $ io, $ template)
Compile given template.
This doesn't check recompilationMode setting, so it may be used to forcibly recompile template. It doesn't use DSN - you must provide correct I/O driver object.
Parameters:
[in] $io I/O driver
[in] $template Template name
Definition at line 438 of file Environment.php.
Referenced by include_().
TemplateEnviron::include_ ($ template, $ mode = null, $ returnMeta = false)
Includes template's code into global namespace via I/O driver given in DSN.
I/O system checks recompilationMode (which you may override per-template using $mode parameter) and acts accordingly, recompiling only when it's required either by this setting or template change. Also recursively handles inclusion of template parent.
Parameters:
[in] $template Template name
[in] $mode Per-template recompilation mode override (optional)
[in] $returnMeta If true, then returns metadata instead of including the code
Returns:
Template's class name, as string; or metadata, as array
Definition at line 458 of file Environment.php.
References compile(), and TemplateUtils::parseIODSN().
Referenced by get(), and getMeta().
TemplateEnviron::get ($ template, $ mode = null)
Returns template instance.
Keep in mind that it doesn't cache template objects - every call will result in object construction, which may lead to performance loss. If you want to use internal object cache, use TemplateEnviron::cachedGet.
Parameters:
[in] $template Template ID
[in] $mode Per-template recompilation mode override (optional)
Returns:
Template subclass instance - an template object
See also:
TemplateEnviron::include_
TemplateEnviron::cachedGet
Definition at line 487 of file Environment.php.
References include_().
TemplateEnviron::getMeta ($ template, $ mode = null)
Returns user-defined template metadata.
It will trigger the compilation, if neccessary. Keep in mind, that the core doesn't cache the metadata. Every call will result in I/O, array unserialization and array filtering.
Parameters:
[in] $template Template ID
[in] $mode Per-template recompilation mode override (optional)
Returns:
Metadata array
Definition at line 501 of file Environment.php.
References include_().
TemplateEnviron::cachedGet ($ template, $ mode = null)
Cached version of TemplateEnviron::get.
Parameters:
[in] $template Template ID
[in] $mode Per-template recompilation mode override (optional)
Returns:
Template subclass instance - an template object
See also:
TemplateEnviron::$templateCache
Definition at line 522 of file Environment.php.
Referenced by render().
TemplateEnviron::render ($ template, array $ context, $ mode = null)
Render the template directly.
Uses internal cache.
Parameters:
[in] $template Template ID
[in] $context Context array
[in] $mode Per-template recompilation mode override (optional)
See also:
Template::render
TemplateEnviron::cachedGet
Definition at line 538 of file Environment.php.
References cachedGet().
Member Data Documentation
const TemplateEnviron::RECOMPILE_ALWAYS = 1
One of recompilation modes - always recompile.
Examples:
02_settings.php.
Definition at line 202 of file Environment.php.
Referenced by TemplateStringIO::upToDate(), and TemplateFileIO::upToDate().
const TemplateEnviron::RECOMPILE_IF_CHANGED = 0
One of recompilation modes - recompile only when necessary (default).
Definition at line 206 of file Environment.php.
Referenced by TemplateFileIO::upToDate().
const TemplateEnviron::RECOMPILE_NEVER = -1
One of recompilation modes - never recompile (a.k.a.
performance mode).
Definition at line 210 of file Environment.php.
Referenced by TemplateFileIO::upToDate().
const TemplateEnviron::SECURITY_DISABLE = 0
One of security modes - do not test against the lists.
Definition at line 215 of file Environment.php.
Referenced by TemplateUtils::checkIfAllowed().
const TemplateEnviron::SECURITY_ALLOW_ALL = 1
One of security modes - first allow all, then check 'disallowed' list.
Definition at line 219 of file Environment.php.
Referenced by TemplateUtils::checkIfAllowed().
const TemplateEnviron::SECURITY_ALLOW_DENY = 2
One of security modes - first check 'allowed' list, then 'disallowed'.
Definition at line 223 of file Environment.php.
Referenced by TemplateUtils::checkIfAllowed().
const TemplateEnviron::SECURITY_DENY_ALLOW = 3
One of security modes - first check 'disallowed' list, then 'allowed'.
Definition at line 227 of file Environment.php.
Referenced by TemplateUtils::checkIfAllowed().
const TemplateEnviron::SECURITY_DENY_ALL = 4
One of security modes - first disallow all, then check 'allowed' list.
Examples:
08_security.php.
Definition at line 231 of file Environment.php.
Referenced by TemplateUtils::checkIfAllowed().
const TemplateEnviron::SECURITY_MATCH_EVERYTHING = true
May be used instead of allowed or disallowed list, as a wildcard matching everything.
Implemented for greater flexibility than only hardcoded modes specified above.
Definition at line 238 of file Environment.php.
const TemplateEnviron::LOAD_ALL_PLUGINS = true
May be used as loadPlugins setting to always load all available plugins on all search paths.
Definition at line 244 of file Environment.php.
TemplateEnviron::$settings
Default environment settings.
Available settings are:
inputPrefix (string) - will be prefixed to all input filenames. Interpretation is up to the I/O driver. In bundled 'file' I/O: source directory name. In bundled 'string' I/O: not used. By default it's './templates/'.
outputPrefix (string) - will be prefixed to all output filenames. Interpretation is up to the I/O driver. In both bundled I/O drivers ('file' and 'string'): output directory name. By default it's './templates_c/'.
loadPlugins (array) - if it's an array: list of plugins to load when compilation starts. Plugins are not loaded until compilation is required.
loadPlugins (bool) - if it's a boolean (value is not checked, but you should use TemplateEnviron::LOAD_ALL_PLUGINS for better self-documentation): library will gather and load all plugins, on every path given in pluginsPaths. It's also a default behaviour.
pluginsPaths (array) - plugins' search paths. When plugin is loaded, all paths given in this array are searched for plugin's file. See Extending SithTemplate for more information about plugins.
useDefaultPluginsPath (bool) - determines whether default plugins' search path (i.e. SITHTEMPLATE_DIR/plugins/) should be used. Note that it works only on construction (by appending to pluginsPaths) - if you override pluginsPaths later, this setting won't have any effect. By default it's true.
recompilationMode (int) - controls how recompilation is handled. One of TemplateEnviron::RECOMPILE_ALWAYS (templates are recompiled on each request), TemplateEnviron::RECOMPILE_IF_CHANGED (templates are recompiled when modified), or TemplateEnviron::RECOMPILE_NEVER (templates are compiled once and never recompiled). By default it's RECOMPILE_IF_CHANGED.
defaultIODriver (string) - default I/O driver to use. Note that you must register it using TemplateIO::register before you request any template.
autoEscape (bool) - should variables not marked with pseudofilter safe be automatically escaped, using StdLibEx filter escape? Do not enable, if you do not use StdLibEx. Disabled by default.
allowInternalRequest (bool) - should access to super-globals be allowed through {{ internal.request }}? Enabled by default.
allowInternalConstants (bool) - should access to global constants be allowed through {{ internal.const }}? Enabled by default.
restrictIncludeIO (bool) - should all {% include %} calls be restricted to the same I/O driver used in TemplateEnviron::get or TemplateEnviron::cachedGet? Disabled by default. Note that it is only enforced at runtime.
restrictExtendIO (bool) - should all {% extend %} calls be restricted to the same I/O driver used in TemplateEnviron::get or TemplateEnviron::cachedGet? Disabled by default. Note that it is only enforced at compile time.
securityEvalMode (int) - specifies whether and how all plugins, tags, filters and function calls should be tested against security (allow/disallow) lists. One of TemplateEnviron::SECURITY_DISABLE, TemplateEnviron::SECURITY_ALLOW_ALL, TemplateEnviron::SECURITY_ALLOW_DENY, TemplateEnviron::SECURITY_DENY_ALLOW, TemplateEnviron::SECURITY_DENY_ALL. Default is SECURITY_DISABLE.
allowedPlugins (array) - whitelist of entire plugins. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
disallowedPlugins (array) - blacklist of entire plugins. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
allowedTags (array) - whitelist of single tags. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
disallowedTags (array) - blacklist of single tags. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
allowedFilters (array) - whitelist of single filters. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
disallowedFilters (array) - blacklist of single filters. You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING.
allowedFunctions (array) - whitelist of single functions (used in {% call %}). You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING. Note that these are the only lists that have effect not only during compilation, but also on runtime.
disallowedFunctions (array) - blacklist of single functions (used in {% call %}). You can also use TemplateEnviron::SECURITY_MATCH_EVERYTHING. Note that these are the only lists that have effect not only during compilation, but also on runtime.
Definition at line 363 of file Environment.php.
Referenced by __construct().
TemplateEnviron::$templateCache = array()
Internal template objects cache.
Definition at line 399 of file Environment.php.
TemplateEnviron::$compiler = null
Compiler instance.
Created when compilation is required.
Definition at line 404 of file Environment.php.
The documentation for this class was generated from the following file:
Environment.php