SithTemplate: TemplatePlugins Class Reference
TemplatePlugins Class Reference
Handles discovery, registration and utilization of plugins.
Public Member Functions
__construct (array $builtins)
Constructor.
load (TemplateCompilerEx $compiler, $node, $plugin, $pluginFile=null, $noThrow=false)
Load single plugin.
loadMultiple (TemplateCompilerEx $compiler, $node, $plugins)
Load multiple plugins.
known ($type, $name)
Check whether given element is registered.
& get ($type, $name)
Returns handler(s) information for given element.
Public Attributes
$searchPaths = array()
Plugins' search paths.
Private Member Functions
findPlugin ($plugin)
Looks for plugin file on all search paths.
findPlugins ($plugins)
Looks for multiple plugins' files on all search paths.
register ($plugin, ITemplatePlugin $pluginObj, $type, array &$handlers)
Registers given elements.
registerHooks ($plugin, ITemplatePlugin $pluginObj, array &$hooks)
Register given hooks.
Private Attributes
$plugins = array()
Already loaded plugins.
$elements = array()
Elements registry.
Detailed Description
Handles discovery, registration and utilization of plugins.
Definition at line 13 of file Plugins.php.
Constructor & Destructor Documentation
TemplatePlugins::__construct (array $ builtins)
Constructor.
Also handles registration of built-ins.
Parameters:
[in] $builtins Built-in elements to register
Definition at line 32 of file Plugins.php.
Member Function Documentation
TemplatePlugins::load (TemplateCompilerEx $ compiler, $ node, $ plugin, $ pluginFile = null, $ noThrow = false)
Load single plugin.
Parameters:
[in] $compiler TemplateCompilerEx instance
[in] $node Optional TemplateNodeEx instance
[in] $plugin Plugin name
[in] $pluginFile Plugin's full filename (optional)
[in] $noThrow If true, no exception will be thrown on error (boolean false will be returned)
Return values:
true Plugin has been loaded
false Plugin is invalid/non-existant
Definition at line 47 of file Plugins.php.
References TemplateUtils::checkIfAllowed(), TemplateUtils::doesImplement(), TemplateError::E_INVALID_PLUGIN, findPlugin(), and registerHooks().
Referenced by loadMultiple().
TemplatePlugins::loadMultiple (TemplateCompilerEx $ compiler, $ node, $ plugins)
Load multiple plugins.
Parameters:
[in] $compiler TemplateCompilerEx instance
[in] $node Optional TemplateNodeEx instance
[in] $plugins Array (plugins to look for) or boolean ('load all plugins' mode)
Definition at line 90 of file Plugins.php.
References $plugins, findPlugins(), and load().
TemplatePlugins::known ($ type, $ name)
Check whether given element is registered.
Parameters:
[in] $type Element type ('tag', 'filter', 'hook' or 'plugin')
[in] $name Element name
Return values:
true Element is registered
false Element is not registered
Definition at line 104 of file Plugins.php.
& TemplatePlugins::get ($ type, $ name)
Returns handler(s) information for given element.
Doesn't check for element's existence.
Parameters:
[in] $type Element type ('tag', 'filter' or 'hook')
[in] $name Element name
Returns:
Assoc. array
Definition at line 117 of file Plugins.php.
TemplatePlugins::findPlugin ($ plugin) [private]
Looks for plugin file on all search paths.
Parameters:
[in] $plugin Plugin name (as string)
Returns:
Filename or false
See also:
TemplatePlugins::load
Definition at line 128 of file Plugins.php.
Referenced by load().
TemplatePlugins::findPlugins ($ plugins) [private]
Looks for multiple plugins' files on all search paths.
Parameters:
[in] $plugins Plugins (array or boolean)
Returns:
Assoc. array (plugin => file)
See also:
TemplatePlugins::loadMultiple
Definition at line 148 of file Plugins.php.
References $plugins, and TemplateError::E_UNKNOWN_PLUGIN.
Referenced by loadMultiple().
TemplatePlugins::register ($ plugin, ITemplatePlugin $ pluginObj, $ type, array &$ handlers) [private]
Registers given elements.
Parameters:
[in] $plugin Plugin name
[in] $pluginObj Plugin instance
[in] $type Element type ('tag' or 'filter')
[in,out] $handlers Array of handlers
Definition at line 186 of file Plugins.php.
References TemplateError::E_INVALID_HANDLER.
TemplatePlugins::registerHooks ($ plugin, ITemplatePlugin $ pluginObj, array &$ hooks) [private]
Register given hooks.
Parameters:
[in] $plugin Plugin name
[in] $pluginObj Plugin instance
[in,out] $hooks Array of hooks
Definition at line 211 of file Plugins.php.
Referenced by load().
Member Data Documentation
TemplatePlugins::$plugins = array() [private]
Already loaded plugins.
Definition at line 17 of file Plugins.php.
Referenced by findPlugins(), and loadMultiple().
TemplatePlugins::$elements = array() [private]
Elements registry.
Definition at line 21 of file Plugins.php.
TemplatePlugins::$searchPaths = array()
Plugins' search paths.
Reference to 'pluginsPaths' key of TemplateEnviron::$settings.
Definition at line 25 of file Plugins.php.
The documentation for this class was generated from the following file:
Plugins.php