SithTemplate: TemplateCompilerEx Class Reference
TemplateCompilerEx Class Reference
Primary compiler driver.
Public Member Functions
__construct ()
Constructor.
reset ()
Resets compiler to pristine state, and loads plugins specified in 'loadPlugins' setting.
compile (ITemplateIODriver $io, $template)
Compiles given template into output package.
handleChildren (array &$children)
Generates code from given node's children.
createBlock ($block, TemplateNodeEx $node)
Creates code block from raw node.
handleNode (TemplateNodeEx $node)
Creates code from given node.
parseVariableExpression (TemplateNodeEx $node, $variable)
Parses variable expression, and creates runtime PHP access code.
parseFilterChain (TemplateNodeEx $node, $filterExpr, $code)
Handles filter chains.
raise (TemplateNodeEx $node, $message, $code)
Raises an error, appending "(in template <file> somewhere around line <line>)" using given node.
raiseIf ($cond, TemplateNodeEx $node, $message, $code)
Shorthand for conditional call to TemplateCompilerEx::raise.
findAlternativeBranch (TemplateNodeEx $node, $tag)
Used to find and isolate alternative branch of given node, starting with given inline tag.
generateUniqueBlock ($idPrefix, $blockPrefix= 'custom:', $keyLength=5)
Generates prefixed block name that is guaranteed to be unique in current template.
Public Attributes
$settings = null
Current settings (reference to TemplateEnviron::$settings).
$plugins = null
Registry of available plugins.
$loadedPlugins = array()
Registry of loaded plugins (per-template).
$blocks = array()
Already constructed code blocks.
$metadata = array()
Template's metadata.
$className = null
Template's classname.
Private Member Functions
createAST (&$tpl)
Creates and returns an Abstract Syntax Tree of given template.
parserGetNextToken (array &$tokens)
Fetches next token from given stream, preprocesses it, and stores it in TemplateCompilerEx::$parserCurrentToken.
parserEncounteredEndTag (TemplateNodeEx $node, $tag, $type)
Checks whether the parser has encountered ending tag with given name.
createNodeFromToken (TemplateNodeEx $node)
Converts current token's array into the node, and adds it to given node's children.
parseTokenStream (TemplateNodeEx $node, array &$tokens, $parseUntil=null, $blockTagType=null)
Parses token stream until it runs out of tokens, or when it encounters given tag name.
generateCode (TemplateNodeEx $root)
Constructs blocks and generates code for the entire AST.
handleTag (TemplateNodeEx $node)
Handles 'blockTag' and 'inlineTag' nodes.
handleVariable (TemplateNodeEx $node)
Handles 'var' node.
generateVariableAST ($variable)
Generates syntax tree (using nested arrays ATM) from given variable expression.
generateVariableCode (TemplateNodeEx $node, &$ast)
Recursively parses variable AST, and generates PHP access code.
commonVerifyElement (TemplateNodeEx $node, $element, &$name, array &$args)
Verifies correctness of given element.
handleLoadBuiltin (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
Handler for load built-in tag.
handleCommentBuiltin (TemplateCompilerEx $compiler, TemplateNodeEx $node, &$tag, array &$args)
Handler for comment built-in tag.
runHooks ($hookPoint, array $args)
Runs handlers associated with given hook-point.
Private Attributes
$parserCurrentToken = null
Currently processed token.
$parserCurrentLine = 1
Currently processed line (approx).
$parserCurrentFile = null
Currently processed template.
$parserTokenRegexp = '~(\{\%.*?\%\})|(\{\{.*?\}\})|(\{\#.*?\#\})~u'
Regular expression used to split template into tokens.
Detailed Description
Primary compiler driver.
It's responsible for creating the AST, and generating the code.
Warning, large strings and heavy recursion ahead.
Definition at line 29 of file CompilerEx.php.
Constructor & Destructor Documentation
TemplateCompilerEx::__construct ()
Constructor.
Definition at line 82 of file CompilerEx.php.
Member Function Documentation
TemplateCompilerEx::reset ()
Resets compiler to pristine state, and loads plugins specified in 'loadPlugins' setting.
Definition at line 102 of file CompilerEx.php.
Referenced by compile().
TemplateCompilerEx::compile (ITemplateIODriver $ io, $ template)
Compiles given template into output package.
Parameters:
[in] $io Used I/O driver
[in] $template Template name
Definition at line 117 of file CompilerEx.php.
References ITemplateIODriver::className(), createAST(), TemplateError::E_IO_LOAD_FAILURE, TemplateError::E_IO_SAVE_FAILURE, generateCode(), ITemplateIODriver::loadTemplate(), TemplateUtils::parseIODSN(), reset(), ITemplateIODriver::saveMetadata(), and ITemplateIODriver::saveTemplate().
TemplateCompilerEx::createAST (&$ tpl) [private]
Creates and returns an Abstract Syntax Tree of given template.
Parameters:
[in] $tpl Source template to parse
Returns:
Root node of the constructed AST
See also:
TemplateNodeEx
Definition at line 174 of file CompilerEx.php.
References parseTokenStream().
Referenced by compile().
TemplateCompilerEx::parserGetNextToken (array &$ tokens) [private]
Fetches next token from given stream, preprocesses it, and stores it in TemplateCompilerEx::$parserCurrentToken.
Parameters:
[in,out] $tokens Token stream (array of tokens)
Return values:
false When there is no more tokens in the stream
true Otherwise
Definition at line 191 of file CompilerEx.php.
References TemplateUtils::split(), and TemplateUtils::splitEscaped().
Referenced by parseTokenStream().
TemplateCompilerEx::parserEncounteredEndTag (TemplateNodeEx $ node, $ tag, $ type) [private]
Checks whether the parser has encountered ending tag with given name.
Parameters:
[in] $node Currently processed node
[in] $tag Tag name to look for ('end' is automatically prepended)
[in] $type Tag type - if ignore, then invalid ending tags will be ignored
Return values:
false When $tag is null, current token's type is not 'tag' or parser has not encountered the tag yet
true When the tag has been found
Definition at line 235 of file CompilerEx.php.
References TemplateError::E_INVALID_SYNTAX.
Referenced by parseTokenStream().
TemplateCompilerEx::createNodeFromToken (TemplateNodeEx $ node) [private]
Converts current token's array into the node, and adds it to given node's children.
Parameters:
[in,out] $node Node to append child to
Definition at line 261 of file CompilerEx.php.
References TemplateNodeEx::addChild().
Referenced by parseTokenStream().
TemplateCompilerEx::parseTokenStream (TemplateNodeEx $ node, array &$ tokens, $ parseUntil = null, $ blockTagType = null) [private]
Parses token stream until it runs out of tokens, or when it encounters given tag name.
Parameters:
[in,out] $node Currently processed node, newly constructed children will be appended to it
[in,out] $tokens Token stream
[in] $parseUntil If not null, then parser will halt when it encounters tag with that name
[in] $blockTagType Type of the block tag (either block or ignore)
Definition at line 274 of file CompilerEx.php.
References createNodeFromToken(), parserEncounteredEndTag(), and parserGetNextToken().
Referenced by createAST().
TemplateCompilerEx::generateCode (TemplateNodeEx $ root) [private]
Constructs blocks and generates code for the entire AST.
Parameters:
[in] $root Root node of the AST
Returns:
Array of the constructed code blocks
Todo:
Is it needed, or maybe TemplateCompilerEx::compile should do it?
Definition at line 317 of file CompilerEx.php.
References createBlock().
Referenced by compile().
TemplateCompilerEx::handleChildren (array &$ children)
Generates code from given node's children.
Accepts array instead of TemplateNodeEx for greater flexibility.
Parameters:
[in] $children Array to process
Returns:
Code as string
Definition at line 330 of file CompilerEx.php.
References handleNode().
Referenced by TemplateStdLibExPlugin::commonIfEqual(), TemplateStdLibExPlugin::handleTAutoEscape(), TemplateStdLibExPlugin::handleTFor(), TemplateStdLibExPlugin::handleTIf(), TemplateStdLibExPlugin::handleTIfChanged(), and TemplateStdLibExPlugin::handleTSpaceless().
TemplateCompilerEx::createBlock ($ block, TemplateNodeEx $ node)
Creates code block from raw node.
Part of exposed compiler API.
Parameters:
[in] $block Name of the block - in form of loop:XXX or block:XXX.
[in] $node Node to process
See also:
TemplateCompilerEx::handleChildren
Definition at line 345 of file CompilerEx.php.
Referenced by generateCode(), TemplateStdLibExPlugin::handleTBlock(), and TemplateStdLibExPlugin::handleTFilter().
TemplateCompilerEx::handleNode (TemplateNodeEx $ node)
Creates code from given node.
Parameters:
[in] $node Node to process
Returns:
Code as string
Todo:
Maybe it should be merged with TemplateCompilerEx::handleChildren?
Definition at line 356 of file CompilerEx.php.
Referenced by handleChildren().
TemplateCompilerEx::handleTag (TemplateNodeEx $ node) [private]
Handles 'blockTag' and 'inlineTag' nodes.
Calls proper tag handler (see Extending: handlers).
Parameters:
[in] $node Tag node to process
Returns:
Code as string
Definition at line 372 of file CompilerEx.php.
TemplateCompilerEx::handleVariable (TemplateNodeEx $ node) [private]
Handles 'var' node.
Parameters:
[in] $node Variable node to process
Returns:
Code as string
Definition at line 401 of file CompilerEx.php.
TemplateCompilerEx::parseVariableExpression (TemplateNodeEx $ node, $ variable)
Parses variable expression, and creates runtime PHP access code.
Parameters:
[in] $node Source node
[in] $variable Variable expression to parse
Returns:
Array(access code, existence checking code)
Definition at line 423 of file CompilerEx.php.
References TemplateUtils::escape().
Referenced by TemplateStdLibExPlugin::commonIfEqual(), TemplateStdLibExPlugin::handleTCycle(), TemplateStdLibExPlugin::handleTFirstOf(), TemplateStdLibExPlugin::handleTFor(), TemplateStdLibExPlugin::handleTIfChanged(), TemplateStdLibExPlugin::handleTInclude(), TemplateStdLibExPlugin::handleTNow(), and TemplateStdLibExPlugin::parseIfExpression().
TemplateCompilerEx::generateVariableAST ($ variable) [private]
Generates syntax tree (using nested arrays ATM) from given variable expression.
Parameters:
[in] $variable Variable expression to parse
Returns:
Arrayized AST
Definition at line 442 of file CompilerEx.php.
TemplateCompilerEx::generateVariableCode (TemplateNodeEx $ node, &$ ast) [private]
Recursively parses variable AST, and generates PHP access code.
Parameters:
[in] $node Source node
[in] $ast AST to process
Returns:
Access code
Definition at line 464 of file CompilerEx.php.
TemplateCompilerEx::parseFilterChain (TemplateNodeEx $ node, $ filterExpr, $ code)
Handles filter chains.
Wraps given code, and returns new one.
Parameters:
[in] $node Filter chain source node
[in] $filterExpr Filter chain expression (e.g. a|b|c:d)
[in] $code Code to wrap in filters
Returns:
New code that uses filters
Definition at line 528 of file CompilerEx.php.
References TemplateUtils::escape(), TemplateUtils::split(), and TemplateUtils::splitEscaped().
Referenced by TemplateStdLibExPlugin::commonIfEqual(), TemplateStdLibExPlugin::handleTFilter(), TemplateStdLibExPlugin::handleTNow(), and TemplateStdLibExPlugin::parseIfExpression().
TemplateCompilerEx::commonVerifyElement (TemplateNodeEx $ node, $ element, &$ name, array &$ args) [private]
Verifies correctness of given element.
Checks whether:
Element exists
Element's handler is callable
Enough arguments have been provided
Parameters:
[in] $node Template node representing element
[in] $element Element type - 'tag' or 'filter'
[in] $name Element's name
[in] $args Element's arguments
Returns:
Element's info array
Definition at line 580 of file CompilerEx.php.
References TemplateUtils::checkIfAllowed(), TemplateError::E_INVALID_HANDLER, TemplateError::E_INVALID_SYNTAX, TemplateError::E_UNKNOWN_FILTER, TemplateError::E_UNKNOWN_TAG, TemplateUtils::panic(), and TemplateUtils::strip().
TemplateCompilerEx::handleLoadBuiltin (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args) [private]
Handler for load built-in tag.
For handlers reference, see Extending: handlers. For standard and built-in tags reference, see Standard tags.
Parameters:
[in] $compiler Compiler handle (TemplateCompilerEx instance)
[in] $node Node handle (TemplateNodeEx instance, see Extending: AST nodes)
[in] $tag Tag name (as string)
[in] $args Tag arguments (as array)
Definition at line 628 of file CompilerEx.php.
References TemplateError::E_UNKNOWN_PLUGIN.
TemplateCompilerEx::handleCommentBuiltin (TemplateCompilerEx $ compiler, TemplateNodeEx $ node, &$ tag, array &$ args) [private]
Handler for comment built-in tag.
For handlers reference, see Extending: handlers. For standard and built-in tags reference, see Standard tags.
Parameters:
[in] $compiler Compiler handle (TemplateCompilerEx instance)
[in] $node Node handle (TemplateNodeEx instance, see Extending: AST nodes)
[in] $tag Tag name (as string)
[in] $args Tag arguments (as array)
Definition at line 649 of file CompilerEx.php.
TemplateCompilerEx::raise (TemplateNodeEx $ node, $ message, $ code)
Raises an error, appending "(in template <file> somewhere around line <line>)" using given node.
Parameters:
[in] $node Node producing an error
[in] $message Error message
[in] $code Error code
See also:
TemplateError
Definition at line 665 of file CompilerEx.php.
Referenced by TemplateStdLibExPlugin::handleTFor().
TemplateCompilerEx::raiseIf ($ cond, TemplateNodeEx $ node, $ message, $ code)
Shorthand for conditional call to TemplateCompilerEx::raise.
Won't raise if $cond is false.
Parameters:
[in] $cond Condition value as boolean
[in] $node Node producing an error
[in] $message Error message
[in] $code Error code
See also:
TemplateError
Definition at line 682 of file CompilerEx.php.
Referenced by TemplateStdLibExPlugin::commonIfEqual(), TemplateStdLibExPlugin::handleTAutoEscape(), TemplateStdLibExPlugin::handleTBlock(), TemplateStdLibExPlugin::handleTCycle(), TemplateStdLibExPlugin::handleTExtends(), TemplateStdLibExPlugin::handleTFirstOf(), TemplateStdLibExPlugin::handleTFor(), TemplateStdLibExPlugin::handleTIfChanged(), TemplateStdLibExPlugin::handleTTemplateTag(), TemplateStdLibExPlugin::parseIfExpression(), and TemplateStdLibExPlugin::parseIfExpressionCheckParens().
TemplateCompilerEx::findAlternativeBranch (TemplateNodeEx $ node, $ tag)
Used to find and isolate alternative branch of given node, starting with given inline tag.
Can be used wherever alternative (e.g. {% else %}) branch cannot be implemented by simply inlining some code (e.g. } else {).
Parameters:
[in] $node Current node
[in] $tag Tag starting alternative branch
Returns:
Array(main nodes, alternative branch nodes)
Definition at line 695 of file CompilerEx.php.
Referenced by TemplateStdLibExPlugin::handleTFor(), and TemplateStdLibExPlugin::handleTIfChanged().
TemplateCompilerEx::generateUniqueBlock ($ idPrefix, $ blockPrefix = 'custom:', $ keyLength = 5)
Generates prefixed block name that is guaranteed to be unique in current template.
By default generates 5-character unique key using combination of uniqid, mt_rand and md5. Beware: potential infinite loop - if key length is too small, then key space might be exhausted, which will lead to infinite loop in this function. Increase $keyLength if your usage could lead to this condition.
Parameters:
[in] $idPrefix uniqid prefix
[in] $blockPrefix Unique key will be prefixed with this. Default: custom:.
[in] $keyLength Length of generated key. Must be lower than 32. Default: 5.
Definition at line 729 of file CompilerEx.php.
References TemplateUtils::panic().
Referenced by TemplateStdLibExPlugin::handleTFor(), and TemplateStdLibExPlugin::handleTIfChanged().
TemplateCompilerEx::runHooks ($ hookPoint, array $ args) [private]
Runs handlers associated with given hook-point.
Every handler might return true boolean value, to break the chain and finish hook execution.
Parameters:
[in] $hookPoint Hook-point to execute
[in] $args Array of hook arguments
Return values:
true Some handler has broken the chain
false All handlers have been executed, and none has broken the chain
Definition at line 756 of file CompilerEx.php.
References TemplateError::E_INVALID_HANDLER, and TemplateUtils::strip().
Member Data Documentation
TemplateCompilerEx::$settings = null
Current settings (reference to TemplateEnviron::$settings).
Definition at line 33 of file CompilerEx.php.
TemplateCompilerEx::$plugins = null
Registry of available plugins.
TemplatePlugins instance.
Definition at line 39 of file CompilerEx.php.
TemplateCompilerEx::$loadedPlugins = array()
Registry of loaded plugins (per-template).
Definition at line 43 of file CompilerEx.php.
TemplateCompilerEx::$parserCurrentToken = null [private]
Currently processed token.
Assoc. array containing two keys - 'type' and 'content'.
Definition at line 50 of file CompilerEx.php.
TemplateCompilerEx::$parserCurrentLine = 1 [private]
Currently processed line (approx).
Definition at line 54 of file CompilerEx.php.
TemplateCompilerEx::$parserCurrentFile = null [private]
Currently processed template.
Definition at line 58 of file CompilerEx.php.
TemplateCompilerEx::$parserTokenRegexp = '~(\{\%.*?\%\})|(\{\{.*?\}\})|(\{\#.*?\#\})~u' [private]
Regular expression used to split template into tokens.
Definition at line 62 of file CompilerEx.php.
TemplateCompilerEx::$blocks = array()
Already constructed code blocks.
Definition at line 68 of file CompilerEx.php.
TemplateCompilerEx::$metadata = array()
Template's metadata.
Definition at line 72 of file CompilerEx.php.
TemplateCompilerEx::$className = null
Template's classname.
Definition at line 76 of file CompilerEx.php.
The documentation for this class was generated from the following file:
CompilerEx.php