SithTemplate: TemplateFileIO Class Reference
TemplateFileIO Class Reference
File I/O implementation.
Public Member Functions
upToDate (array &$settings, &$template, $mode)
includeCode (array &$settings, &$template)
className (array &$settings, &$template)
loadTemplate (array &$settings, &$template)
loadMetadata (array &$settings, &$template)
saveTemplate (array &$settings, &$template, &$code)
saveMetadata (array &$settings, &$template, array &$metadata)
Protected Member Functions
pfn (array &$settings, &$template)
Detailed Description
File I/O implementation.
Definition at line 78 of file IO.php.
Member Function Documentation
TemplateFileIO::pfn (array &$ settings, &$ template) [protected]
Reimplemented in TemplateStringIO.
Definition at line 84 of file IO.php.
Referenced by includeCode(), loadMetadata(), loadTemplate(), saveMetadata(), saveTemplate(), and upToDate().
TemplateFileIO::upToDate (array &$ settings, &$ template, $ mode)
Should check whether given template is up-to-date.
If driver uses recompilationMode setting, then it should use supplied $mode argument instead, to allow per-template mode override. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $mode Recompilation mode
Return values:
true Template is up-to-date - no (re)compilation is needed
false Template must be (re)compiled
Implements ITemplateIODriver.
Reimplemented in TemplateStringIO.
Definition at line 93 of file IO.php.
References TemplateError::E_INVALID_ARGUMENT, TemplateError::E_IO_LOAD_FAILURE, pfn(), TemplateEnviron::RECOMPILE_ALWAYS, TemplateEnviron::RECOMPILE_IF_CHANGED, and TemplateEnviron::RECOMPILE_NEVER.
TemplateFileIO::includeCode (array &$ settings, &$ template)
Should include template's code into global namespace.
It must ensure that no code redefinition will happen. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Included class name
Implements ITemplateIODriver.
Reimplemented in TemplateStringIO.
Definition at line 122 of file IO.php.
References className(), TemplateError::E_IO_LOAD_FAILURE, and pfn().
TemplateFileIO::className (array &$ settings, &$ template)
Should return template's classname.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Class name
Implements ITemplateIODriver.
Reimplemented in TemplateStringIO.
Definition at line 140 of file IO.php.
Referenced by includeCode().
TemplateFileIO::loadTemplate (array &$ settings, &$ template)
Should read template source code as whole, and return it.
SithTemplate ensures that this will be called only when compilation is needed, so no additional checks are needed. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Whole template source
Implements ITemplateIODriver.
Definition at line 145 of file IO.php.
References pfn().
TemplateFileIO::loadMetadata (array &$ settings, &$ template)
Should read template's metadata, and return it.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Template metadata or false.
Implements ITemplateIODriver.
Definition at line 151 of file IO.php.
References pfn().
TemplateFileIO::saveTemplate (array &$ settings, &$ template, &$ code)
Should save compiled template code.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $code Template code
Return values:
true Template has been saved
false An error occured
Implements ITemplateIODriver.
Definition at line 157 of file IO.php.
References pfn().
TemplateFileIO::saveMetadata (array &$ settings, &$ template, array &$ metadata)
Should save template metadata.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $metadata Metadata
Return values:
true Metadata has been saved
false An error occured
Implements ITemplateIODriver.
Definition at line 163 of file IO.php.
References pfn().
The documentation for this class was generated from the following file:
IO.php