SithTemplate: TemplateStringIO Class Reference
TemplateStringIO Class Reference
String I/O implementation.
Public Member Functions
upToDate (array &$settings, &$template, $mode)
includeCode (array &$settings, &$template)
className (array &$settings, &$template)
Protected Member Functions
pfn (array &$settings, &$template)
Detailed Description
String I/O implementation.
Definition at line 172 of file IO.php.
Member Function Documentation
TemplateStringIO::pfn (array &$ settings, &$ template) [protected]
Reimplemented from TemplateFileIO.
Definition at line 173 of file IO.php.
Referenced by includeCode(), and upToDate().
TemplateStringIO::upToDate (array &$ settings, &$ template, $ mode)
Should check whether given template is up-to-date.
If driver uses recompilationMode setting, then it should use supplied $mode argument instead, to allow per-template mode override. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $mode Recompilation mode
Return values:
true Template is up-to-date - no (re)compilation is needed
false Template must be (re)compiled
Reimplemented from TemplateFileIO.
Definition at line 185 of file IO.php.
References pfn(), and TemplateEnviron::RECOMPILE_ALWAYS.
TemplateStringIO::includeCode (array &$ settings, &$ template)
Should include template's code into global namespace.
It must ensure that no code redefinition will happen. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Included class name
Reimplemented from TemplateFileIO.
Definition at line 193 of file IO.php.
References className(), TemplateError::E_IO_LOAD_FAILURE, and pfn().
TemplateStringIO::className (array &$ settings, &$ template)
Should return template's classname.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Class name
Reimplemented from TemplateFileIO.
Definition at line 210 of file IO.php.
Referenced by includeCode().
The documentation for this class was generated from the following file:
IO.php