SithTemplate: ITemplateIODriver Interface Reference
ITemplateIODriver Interface Reference
Interface required for all I/O drivers.
Public Member Functions
upToDate (array &$settings, &$template, $mode)
Should check whether given template is up-to-date.
includeCode (array &$settings, &$template)
Should include template's code into global namespace.
className (array &$settings, &$template)
Should return template's classname.
loadTemplate (array &$settings, &$template)
Should read template source code as whole, and return it.
loadMetadata (array &$settings, &$template)
Should read template's metadata, and return it.
saveTemplate (array &$settings, &$template, &$code)
Should save compiled template code.
saveMetadata (array &$settings, &$template, array &$metadata)
Should save template metadata.
Detailed Description
Interface required for all I/O drivers.
I/O machinery is separated from template plugins.
Definition at line 15 of file IIODriver.php.
Member Function Documentation
ITemplateIODriver::upToDate (array &$ settings, &$ template, $ mode)
Should check whether given template is up-to-date.
If driver uses recompilationMode setting, then it should use supplied $mode argument instead, to allow per-template mode override. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $mode Recompilation mode
Return values:
true Template is up-to-date - no (re)compilation is needed
false Template must be (re)compiled
Implemented in TemplateFileIO, and TemplateStringIO.
ITemplateIODriver::includeCode (array &$ settings, &$ template)
Should include template's code into global namespace.
It must ensure that no code redefinition will happen. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Included class name
Implemented in TemplateFileIO, and TemplateStringIO.
ITemplateIODriver::className (array &$ settings, &$ template)
Should return template's classname.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Class name
Implemented in TemplateFileIO, and TemplateStringIO.
Referenced by TemplateCompilerEx::compile().
ITemplateIODriver::loadTemplate (array &$ settings, &$ template)
Should read template source code as whole, and return it.
SithTemplate ensures that this will be called only when compilation is needed, so no additional checks are needed. Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Whole template source
Implemented in TemplateFileIO.
Referenced by TemplateCompilerEx::compile().
ITemplateIODriver::loadMetadata (array &$ settings, &$ template)
Should read template's metadata, and return it.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
Returns:
Template metadata or false.
Implemented in TemplateFileIO.
ITemplateIODriver::saveTemplate (array &$ settings, &$ template, &$ code)
Should save compiled template code.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $code Template code
Return values:
true Template has been saved
false An error occured
Implemented in TemplateFileIO.
Referenced by TemplateCompilerEx::compile().
ITemplateIODriver::saveMetadata (array &$ settings, &$ template, array &$ metadata)
Should save template metadata.
Although parameters are supplied via reference, they should not be modified in any way.
Parameters:
[in] $settings Settings array, see TemplateEnviron::$settings
[in] $template Template name
[in] $metadata Metadata
Return values:
true Metadata has been saved
false An error occured
Implemented in TemplateFileIO.
Referenced by TemplateCompilerEx::compile().
The documentation for this interface was generated from the following file:
IIODriver.php